import { Animation } from './animation';
import { Counter } from './counter';
import { DragBehaviour } from './dragBehaviour';
import { EventDispatcher } from './eventDispatcher';
import { Mover } from './mover';
import { Options } from './options';
import { ScrollBounds } from './scrollBounds';
import { ScrollLooper } from './scrollLooper';
import { ScrollProgress } from './scrollProgress';
import { ScrollTo } from './scrollTo';
import { SlideLooper } from './slideLooper';
import { Translate } from './translate';
import { Vector1D } from './vector1d';
export declare type Engine = {
    animation: Animation;
    scrollBounds: ScrollBounds;
    scrollLooper: ScrollLooper;
    scrollProgress: ScrollProgress;
    index: Counter;
    indexPrevious: Counter;
    indexGroups: number[][];
    mover: Mover;
    pointer: DragBehaviour;
    slideLooper: SlideLooper;
    target: Vector1D;
    translate: Translate;
    scrollTo: ScrollTo;
};
export declare function Engine(root: HTMLElement, container: HTMLElement, slides: HTMLElement[], options: Options, events: EventDispatcher): Engine;
